Schrodinger-Hat/osday

- constants/index.ts
- styles/globals.css
Fixes issues #36 and a few other style issues
> fixed issue 36

- pages/agenda.tsx
- pages/venue.tsx
- public/locales/en.json
- public/locales/it.json
> i18n for Italian language

- public/locales/es.json
> Add Spanish Translation to public/locales/es.json

- components/Header.tsx
- styles/globals.css
- utils/index.ts
> added notification menu

- components/Header.tsx
- styles/globals.css
> Add languageSwitcher

- public/locales/en.json
- public/locales/es.json
- public/locales/fr.json
- public/locales/it.json
> Media and Community partner description

- components/TalkCard.tsx
- constants/index.ts
- pages/speakers.tsx
- public/locales/en.json
- public/locales/es.json
- public/locales/fr.json
- public/locales/it.json
- styles/globals.css
Added new resources to Speakers page and changes look of cards and btn background to linear gradient. What do you think?
Also, not using images will allow us for better a11y and performance
Scores are 100% now https://gtmetrix.com/reports/deploy-preview-64--keen-banoffee-86ed50.netlify.app/Ma4hsJtM/
> changes to cards and added speaker resources

- components/SponsorshipTier.tsx
- pages/sponsor.tsx
- public/locales/en.json
- public/locales/es.json
- public/locales/fr.json
- public/locales/it.json
- styles/globals.css
> Send email button in sponsorship card

- pages/500.tsx
- public/locales/en.json
- public/locales/es.json
- public/locales/fr.json
- public/locales/it.json
> fix: add 500 err page and fix i18n format message

- components/Footer.tsx
> fix: add fb, ig links

- components/Header.tsx
- public/locales/en.json
- public/locales/es.json
- public/locales/fr.json
- public/locales/it.json
> i18n: add notification labels and date in hero hp

- components/Footer.tsx
- public/icons/opencollective.svg
> feat: add opencollective icon

- components/Header.tsx
- package-lock.json
- styles/globals.css
> feat: add sticky header with transition

- components/Layout.tsx
- styles/globals.css
> fix: closes #60, fix background gradient and image

- components/Footer.tsx
- components/Hero.tsx
- components/Main.tsx
- pages/code-of-conduct.tsx
- public/locales/en.json
- public/locales/es.json
- public/locales/fr.json
- public/locales/it.json
- styles/globals.css
> Code of Conduct page

- styles/globals.css
> fix: mobile, closes #60

- components/Header.tsx
- components/Hero.tsx
- pages/about.tsx
- pages/agenda.tsx
- pages/cfp.tsx
- pages/code-of-conduct.tsx
- pages/dei.tsx
- pages/policies.tsx
- pages/rules.tsx
- pages/speakers.tsx
- pages/sponsor.tsx
- pages/venue.tsx
- styles/globals.css
> feat: add ticket CTA btn, closes #84

- components/SponsorTable.tsx
> Sponsor table review

- public/locales/en.json
- public/locales/es.json
- public/locales/fr.json
- public/locales/it.json
> feat: improve about description

- components/Footer.tsx
- pages/venue.tsx
This PR fixes #117 
Replaced Twitter handle from `OSDayDev` to `schrodinger_hat`
> Update Twitter handle

- components/SponsorshipTable.tsx
- pages/sponsor.tsx
- public/locales/en.json
- public/locales/es.json
- public/locales/fr.json
- public/locales/it.json
> Added CTA buttons and i18n

- components/Header.tsx
- public/locales/en.json
- public/locales/es.json
- public/locales/fr.json
- public/locales/it.json
> feature: add nana bianca notification

- components/Header.tsx
- public/locales/en.json
- public/locales/es.json
- public/locales/fr.json
- public/locales/it.json
> Notification dimension

- components/Main.tsx
- pages/about.tsx
- pages/agenda.tsx
- pages/cfp.tsx
- pages/cfv.tsx
- pages/code-of-conduct.tsx
- pages/cookie.tsx
- pages/dei.tsx
- pages/index.tsx
- pages/policies.tsx
- pages/rules.tsx
- pages/speakers.tsx
- pages/sponsor.tsx
- pages/venue.tsx
- public/locales/en.json
- public/locales/es.json
- public/locales/fr.json
- public/locales/it.json
> Added missing date and other infos

- components/SponsorshipTable.tsx
Changed behaviour of sponsorship table to be more logical in vertical…
> Sponsorship tiers ordering

- components/Header.tsx
- public/locales/en.json
- public/locales/es.json
- public/locales/fr.json
- public/locales/it.json
> feat: add photo in nav
